SELECT * FROM ACCOUNT;
SELECT * FROM ACCOUNT WHERE ACCOUNT_ID = 'tester';

SELECT * FROM SHOPPING_LIST;
SELECT * FROM ITEM;
SELECT * FROM ITEM_OPTION;
SELECT * FROM ITEM_CATEGORY;

INSERT INTO ITEM VALUES(0, 1, '마이페이지', '마이페이지', 1);
INSERT INTO ITEM VALUES(ITEM_SEQ.NEXTVAL, 1, '상품이름1', '상품내용1', 10000);
INSERT INTO ITEM VALUES(ITEM_SEQ.NEXTVAL, 1, '상품이름2', '상품내용2', 10);
INSERT INTO ITEM_OPTION VALUES(ITEM_OPTION_SEQ.NEXTVAL, 1, 'S', '검은색', 100);
INSERT INTO ITEM_OPTION VALUES(ITEM_OPTION_SEQ.NEXTVAL, 1, 'M', '검은색', 80);
INSERT INTO ITEM_OPTION VALUES(ITEM_OPTION_SEQ.NEXTVAL, 1, 'M', '회색', 50);
INSERT INTO SHOPPING_LIST VALUES(SHOPPING_LIST_SEQ.NEXTVAL, 'ha1015', 1, 1, 1);
INSERT INTO SHOPPING_LIST VALUES(SHOPPING_LIST_SEQ.NEXTVAL, 'ha1015', 1, 2, 3);
INSERT INTO SHOPPING_LIST VALUES(SHOPPING_LIST_SEQ.NEXTVAL, 'ha1015', 1, 10, 2);

SELECT * FROM SHOPPING_LIST WHERE ACCOUNT_ID = 'ha1015' ORDER BY 1;

SELECT * FROM ZZIM_LIST;
INSERT INTO ZZIM_LIST VALUES(ZZIM_LIST_SEQ.NEXTVAL, 'ha1015', 1);
INSERT INTO ZZIM_LIST VALUES(ZZIM_LIST_SEQ.NEXTVAL, 'ha1015', 2);

SELECT * FROM COUPON;
SELECT * FROM GIVE_COUPON;

INSERT INTO COUPON VALUES(COUPON_SEQ.NEXTVAL, '쿠폰1', SYSDATE, SYSDATE, 3, 100);
INSERT INTO GIVE_COUPON VALUES(GIVE_COUPON_SEQ.NEXTVAL, 1, 'ha1015');

SELECT * FROM REPORT;
SELECT * FROM REPORT_REASON;
SELECT * FROM POST;
SELECT * FROM BOARD;


INSERT INTO REPORT_REASON VALUES(REPORT_REASON_SEQ.NEXTVAL, '사유1');
INSERT INTO REPORT_REASON VALUES(REPORT_REASON_SEQ.NEXTVAL, '사유2');
INSERT INTO POST VALUES(POST_SEQ.NEXTVAL, 'ha1015', 0, '제목1', '내용1', 0, 0, SYSDATE);
INSERT INTO REPORT VALUES(REPORT_SEQ.NEXTVAL, 1, 'ha1015', 'ha1015', 1, SYSDATE, '이러저러해서 신고합니다.', NULL, NULL);

SELECT * FROM REPORT R JOIN REPORT_REASON RR ON R.REPORT_REASON_ID = RR.REPORT_REASON_ID;

INSERT INTO QUESTION VALUES(QUESTION_SEQ.NEXTVAL, 0, 'ha1015', '문의123', '문의입니다.1', SYSDATE, 0, NULL, NULL, NULL);
ALTER TABLE QUESTION DROP CONSTRAINT SYS_C0018254;
ALTER TABLE QUESTION ADD CONSTRAINT QUESTION_RESULT_CK CHECK(RESULT IN ('0', '1'));