SELECT * FROM ACCOUNT;
SELECT * FROM ACCOUNT WHERE ACCOUNT_ID = 'tester';

SELECT * FROM SHOPPING_LIST;
SELECT * FROM ITEM;
SELECT * FROM ITEM_OPTION;
SELECT * FROM ITEM_CATEGORY;

SELECT * FROM ITEM_OPTION WHERE ITEM_ID = '1' AND AMOUNT NOT IN ('0');
SELECT ITEM_SIZE FROM ITEM_OPTION WHERE ITEM_ID = '1' AND AMOUNT NOT IN ('0') GROUP BY ITEM_SIZE;
SELECT COLOR FROM ITEM_OPTION WHERE ITEM_ID = '1' AND AMOUNT NOT IN ('0') GROUP BY COLOR;

INSERT INTO ITEM VALUES(0, 1, '마이페이지', '마이페이지', 1);
INSERT INTO ITEM VALUES(ITEM_SEQ.NEXTVAL, 1, '상품이름1', '상품내용1', 10000);
INSERT INTO ITEM VALUES(ITEM_SEQ.NEXTVAL, 1, '상품이름2', '상품내용2', 10);
INSERT INTO ITEM_OPTION VALUES(ITEM_OPTION_SEQ.NEXTVAL, 1, 'S', '검은색', 100);
INSERT INTO ITEM_OPTION VALUES(ITEM_OPTION_SEQ.NEXTVAL, 1, 'M', '검은색', 80);
INSERT INTO ITEM_OPTION VALUES(ITEM_OPTION_SEQ.NEXTVAL, 1, 'L', '빨간색', 0);
INSERT INTO SHOPPING_LIST VALUES(SHOPPING_LIST_SEQ.NEXTVAL, 'ha1015', 1, 1, 1);
INSERT INTO SHOPPING_LIST VALUES(SHOPPING_LIST_SEQ.NEXTVAL, 'ha1015', 1, 2, 3);
INSERT INTO SHOPPING_LIST VALUES(SHOPPING_LIST_SEQ.NEXTVAL, 'ha1015', 1, 10, 2);

SELECT * FROM SHOPPING_LIST WHERE ACCOUNT_ID = 'ha1015' ORDER BY 1;

SELECT * FROM ZZIM_LIST;
INSERT INTO ZZIM_LIST VALUES(ZZIM_LIST_SEQ.NEXTVAL, 'ha1015', 1);
INSERT INTO ZZIM_LIST VALUES(ZZIM_LIST_SEQ.NEXTVAL, 'ha1015', 2);

SELECT * FROM COUPON;
SELECT * FROM GIVE_COUPON;

INSERT INTO COUPON VALUES(COUPON_SEQ.NEXTVAL, '쿠폰1', SYSDATE, SYSDATE, 3, 100);
INSERT INTO GIVE_COUPON VALUES(GIVE_COUPON_SEQ.NEXTVAL, 1, 'ha1015');

SELECT * FROM REPORT;
SELECT * FROM REPORT_REASON;
SELECT * FROM POST;
SELECT * FROM BOARD;
SELECT * FROM QUESTION;


INSERT INTO REPORT_REASON VALUES(REPORT_REASON_SEQ.NEXTVAL, '사유1');
INSERT INTO REPORT_REASON VALUES(REPORT_REASON_SEQ.NEXTVAL, '사유2');
INSERT INTO POST VALUES(POST_SEQ.NEXTVAL, 'ha1015', 0, '제목1', '내용1', 0, 0, SYSDATE);
INSERT INTO REPORT VALUES(REPORT_SEQ.NEXTVAL, 1, 'ha1015', 'ha1015', 1, SYSDATE, '이러저러해서 신고합니다.', NULL, NULL);

SELECT * FROM REPORT R JOIN REPORT_REASON RR ON R.REPORT_REASON_ID = RR.REPORT_REASON_ID;

INSERT INTO QUESTION VALUES(QUESTION_SEQ.NEXTVAL, 0, 'ha1015', '문의123', '문의입니다.1', SYSDATE, 0, NULL, NULL, NULL);
ALTER TABLE QUESTION DROP CONSTRAINT SYS_C0018254;
ALTER TABLE QUESTION ADD CONSTRAINT QUESTION_RESULT_CK CHECK(RESULT IN ('0', '1'));

CREATE SEQUENCE COMMENTNUM_SEQ NOCACHE;

INSERT INTO SOCIAL_ACCOUNT VALUES('USER' || SOCIAL_ACCOUNT_SEQ.NEXTVAL, '123456789', '하', NULL, 'k@c.com', NULL, NULL, '하', '2', SYSDATE);
SELECT * FROM SOCIAL_ACCOUNT;
DROP TABLE SOCIAL_ACCOUNT;

CREATE TABLE SOCIAL_ACCOUNT(
	  SOCIAL_ACCOUNT_ID VARCHAR2(50) PRIMARY KEY
	, RAND_ID VARCHAR2(50) NOT NULL
	, NAME VARCHAR2(50)
	, PHONE VARCHAR2(50)
	, EMAIL VARCHAR2(50) NOT NULL
	, ADDRESS VARCHAR2(200)
	, ADDRESS_NO VARCHAR2(50)
	, NICKNAME VARCHAR2(50) NOT NULL
	, LOGIN_TYPE NUMBER CHECK (LOGIN_TYPE >= 1 AND LOGIN_TYPE <= 3)
	, JOINDATE DATE DEFAULT (SYSDATE)
);
CREATE SEQUENCE SOCIAL_ACCOUNT_SEQ NOCACHE;

SELECT * FROM ACCOUNT ORDER BY JOINDATE;

INSERT INTO SOCIAL_ACCOUNT VALUES('USER' || SOCIAL_ACCOUNT_SEQ.NEXTVAL, '109040000028667400000', '달코드', NULL, 'sungha@gmail.com', NULL, NULL, '달코드', '2', SYSDATE);


SELECT COUNT(*) FROM (SELECT * FROM (SELECT * FROM SOLD_HISTORY WHERE ACCOUNT_ID = 'tester') H JOIN SOLD_DETAIL D ON D.SOLD_HISTORY_ID = H.SOLD_HISTORY_ID WHERE ITEM_ID = '2');
SELECT * FROM SOLD_HISTORY;
SELECT * FROM SOLD_DETAIL;
INSERT INTO SOLD_HISTORY VALUES(SOLD_HISTORY_SEQ.NEXTVAL, 'ha1015', 'SEOUL', '김', '010', SYSDATE, '0');
INSERT INTO SOLD_DETAIL VALUES(SOLD_DETAIL_SEQ.NEXTVAL, '1', '5', '1', '1', '0', NULL, NULL, NULL, NULL);

SELECT * FROM IMAGE;
